### ISSUE TITLE
Display source info on hover 

### ISSUE THREAD

**Issue by dhowe** [dhowe/annograms#1]
- [x] fix position of 'from...' line
- [x] ~should always highlight full phrase from meta object (not only words in text)~ maybe no longer relevant(revisit)?
- [x] instead of a single sentence, try X characters before and after
- [x] ellipses should always happen at start unless it includes the start of the source text (A)
- [x] ellipses should always happen at end unless it includes the end of the source text (B)
- [x] if case A or B, then more of the text should be taken from the other end, so as to maintain X characters

Migrated from https://github.com/dhowe/ProPoGen/issues/5

**Comment by Real-John-Cheung** [comment]
now it displays ~140 characters before and after
