### ISSUE TITLE
Add animation for annotateGreedy

### ISSUE THREAD

**Issue by dhowe** [dhowe/annograms#12]
_(first check #3)_

When the current _generate_ button is pushed, each line in the result lazy should appear (hot-linked), one by one, with perhaps a 20-50ms delay, in a separate cell.
<img width="979" alt="image" src="https://user-images.githubusercontent.com/737638/148369940-4eddf493-3c49-4474-b96e-75a7683ffe5a.png">

**Comment by Real-John-Cheung** [comment]
a cell can be added in Observablehq like this
```js
{
  let targetDiv = html`<div></div>`
  annogram.displayAnimated(poem, targetDiv);
  return targetDiv;
}
```
50ms might be too short, currently I set it to 100ms, it can be changed by changing the parameter of the `delay()` function

**Comment by dhowe** [comment]
good work

a few issues:
- [ ] timing way too fast
- [ ] no spaces between lines
- [ ] no spaces between paragraphs

<img width="629" alt="image" src="https://user-images.githubusercontent.com/737638/148568841-2bc50c2a-742d-4756-a50b-e54b433ed029.png">

**Comment by Real-John-Cheung** [comment]
updated api:
```js
 annogram.displayAnimated(poem, targetDiv, (optional) delayInMs, (optional) fadeInAnimationDurationInMs);
```
example
```js
{
  let targetDiv = html`<div></div>`
  annogram.displayAnimated(poem, targetDiv, 500);
  return targetDiv;
}
```
<< no spaces between paragraphs (1st image)
<<source div cutoff on right edge (2nd image)
they are caused by the overflow problem. now the div can be scroll horizontally. but should we add limitation to the width or deal with the scrolling (e.g auto scroll)?

**Comment by dhowe** [comment]
> they are caused by the overflow problem. now the div can be scroll horizontally. but should we add limitation to the width or deal with the scrolling (e.g auto scroll)?

no horizontal scroll, perhaps can set max-width in the function? let's move all these options to an options object

` annogram.displayAnimated(poem, targetDiv, { delayInMs, fadeInAnimationDurationInMs, maxWidth } );`

**Comment by Real-John-Cheung** [comment]
>no horizontal scroll, perhaps can set max-width in the function?

Then we need to decide what to do with the long sentences that are causing overflow...
we can 
1. wrap them (but might be confused with paragraph)
2. change the font size, just like what we do in adlipo

I think the best way would be wrapping them but with some indentation to separate them from paragraph break... like this
```rust
You can see, then,
             then, and
             then, and the
                   and the horse
                   and the horse.
the horse. They said,        //paragraph 
           They said, Here
                said, Here it’s my father’s,
                                my father’s, but he
                                             but he didn’t
                                             but he didn’t say
                                                 he didn’t say a word.
a word. I lie        //paragraph 
       . I lie that I have
               that I have to
                    I have to be
                      have to be the
                           to be the first
                              be the first time
                                 the first time, because I
                                                 because I had
        because I had said to the        //wrap
                      said to the horse,
                      ....
```

**Comment by dhowe** [comment]
yes, this seems a good solution, perhaps with the paragraph indent as another (optional) option

**Comment by dhowe** [comment]
now called asLineAnimation()
