### ISSUE TITLE
Repeated tokens in display (lazy)

### ISSUE THREAD

**Issue by dhowe** [dhowe/annograms#15]
not sure what is causing this, but seems to be a new problem (pre-#14)

![image](https://user-images.githubusercontent.com/737638/148568419-126c3818-cfc5-4666-8133-d332412e565c.png)

**Comment by Real-John-Cheung** [comment]
I think that's because the input for `displayHtml()` should be the lazy data. When put in greedy data the above problem occurs, because the `start` property is incorrect for some reasons...

**Comment by dhowe** [comment]
I will take a look

**Comment by dhowe** [comment]
appears to be fixed
