### ISSUE TITLE
Rework asLineAnimation() for new annotations

### ISSUE THREAD

**Issue by dhowe** [dhowe/annograms#21]
Rework asLineAnimation() function (renamed from displayAnimation()) for new annotations

- [x] support new annotation style
- [x] check punctuation
- [x] handle wrapping of lines with indent
- [x] remove all css from function (also asHtml function)
- [x] add css to observable notebooks
- [x] reduce font-size and line-height
- [x] if possible, first create a div with fixed vertical height that gets filled in with the text
- [ ] ~if possible, adjust z-level for source annotations so they are not blocked by other cells~

**Comment by Real-John-Cheung** [comment]
>if possible, adjust z-level for source annotations so they are not blocked by other cells 

I tried adjust z-level but seems that it doesn't change anything... I think it has something to do with how observable display pinned cells (i.e. the cells whose code is always shown)

**Comment by dhowe** [comment]
perhaps post a question on observable forum?

**Comment by Real-John-Cheung** [comment]
> I think it has something to do with how observable display pinned cells 

Update: 
![圖片](https://user-images.githubusercontent.com/61215358/154059523-e958b9a7-9992-4c40-8a4d-dea0198aa903.png)
![圖片](https://user-images.githubusercontent.com/61215358/154064020-23e57585-726a-45bd-b3db-e9f891ad782c.png)

the executed results of cells (in this cases, our annotations and other stuffs) are rendered in an iframe element (inside hightlighted div) while the source codes are rendered in divs (with id=`cell-xxx`) in same level of the hightlighted div. so adjusting annotations' z-index will not have effect (that will only change the z-index inside the iframe local context). 

observable forum: https://talk.observablehq.com/t/z-index-issue-between-cell-content-and-cell-source-code/6228
