### ISSUE TITLE
Implement autoscrolling

### ISSUE THREAD

**Issue by dhowe** [dhowe/annograms#29]
Lets add a option where there is a fixed size window for the animation (~10 lines) and have it autoscroll (new lines appear at bottom of window, old lines disappear at top)

If this works ok, we can consider continuous generation (with new lines continually being added)

**Comment by dhowe** [comment]
So no vertical scrollbars: the idea is that we have a fixed-height div which begins empty, with enough vertical space for maybe 10-20 lines. Once it is full, when new lines appear at bottom, each line shifts up by one, and the oldest disappears off the top (like a queue). 

And no horizontal scrollbars: as we discussed earlier, lines should wrap and indent if wider than the window


<img width="853" alt="Screenshot 2022-01-20 at 10 54 53 PM" src="https://user-images.githubusercontent.com/737638/150363564-81bf6d6a-c64d-4371-a4e4-9a4e746e4cb1.png">

**Comment by dhowe** [comment]
Also still a problem that we the annotation are not very visible near bottom or right edge:

<img width="225" alt="image" src="https://user-images.githubusercontent.com/737638/150364424-e510bc30-0c82-4c80-9370-7004c3b6fbe2.png">

**Comment by dhowe** [comment]
Not sure this is working as intended:

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/737638/150634655-19f3a031-0108-41d1-8985-3151cb128863.png">

**Comment by dhowe** [comment]
Great. I'm also seeing the alignment problem with punctuation again:

<img width="806" alt="image" src="https://user-images.githubusercontent.com/737638/150637219-cf63da83-3678-478c-a438-05ffa1c31203.png">

**Comment by Real-John-Cheung** [comment]
> I'm also seeing the alignment problem with punctuation again: 

should be fixed with https://github.com/dhowe/annograms/pull/33/commits/da7acf5b6a69b8f3cf38e11fe970857c9f9e4b03
