### ISSUE TITLE
Find and format additional (prose) poems for database

### ISSUE THREAD

**Issue by dhowe** [dhowe/annograms#35]
See the entries in [data](https://github.com/dhowe/annograms/tree/main/data) -- we need at least another book's worth of prose-like poems (contemporary poems after 1900, with sentences rather than _only_ line breaks)

- [ ] locate additional entries for new file
- [ ] format as JSON and submit PR

**Comment by dhowe** [comment]
@StevenZhou01 please include the original as a .txt file in the [text](https://github.com/dhowe/annograms/tree/main/text) folder (update the PR)

**Comment by StevenZhou01** [comment]
Okay!

> @StevenZhou01 please include the original as a .txt file in the [text](https://github.com/dhowe/annograms/tree/main/text) folder (update the PR)

**Comment by StevenZhou01** [comment]
So far, I've uploaded all the Japanese prose poems you sent me earlier and skipped a few poems that don't meet the requirements.
